# Site settings
title: Pankaj Sherchan
description: 'Senior Computer Science and Mathematics Student at SLU<br> Software Developer Intern at GCR. <br> An Aspiring Statistician'
url: 'http://joshgerdes.com' 
baseurl: '/',
project1_url : 'https://github.com/pankajsherchan/API'
google_analytics: 'UA-501066-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Pankaj Sherchan'
  email: pankaj.sherchan@selu.edu
  twitter_username: sherchan_pankaj
  # facebook_username: joshgerdes
  github_username:  pankajsherchan
  linkedin_username:  pankaj-sherchan-09b417a3/

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'src']
